### ISSUE TITLE
针对新系统进行研究和适配

### ISSUE THREAD

**Issue by dawnli-github** [838239178/tk-auto-study#102]
### 内容

系统更换为了验证码重新注册登录，系统的判定也好像不一样了

**Comment by 838239178** [comment]
还能用啊 没有变化啊

发自我的iPhone

在 2022年9月6日，10:00，DawnLi ***@***.***> 写道：

﻿

内容

系统更换为了验证码重新注册登录，系统的判定也好像不一样了

**Comment by dawnli-github** [comment]
是可以用，但是FJ的系统好像换了，我们有通知，我刚才上了微信看确实换了系统还要重新注册了

**Comment by 838239178** [comment]
看了一下，估计是准备要换系统了

**Comment by 838239178** [comment]
系统真垃圾，一堆bug就上了，我都注册不了

**Comment by dawnli-github** [comment]
是的，要一个公众号验证，后面感觉没法用这个模式打卡了

**Comment by 838239178** [comment]
大概率手动抓包找自己的openid就能做到

**Comment by dawnli-github** [comment]
静候大佬佳音

**Comment by 17850773959** [comment]
等待大佬抓包

**Comment by miscdec** [comment]
从日志看，旧接口应该已经失效

HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.%3Cattribute%20'microsecond'%20of%20'datetime.datetime'%20objects%3E&width=58&height=19&num=4 (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.%3Cattribute%20'microsecond'%20of%20'datetime.datetime'%20objects%3E&width=58&height=19&num=4 (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\spiders\tk-auto-study\main.py", line 20, in catch
    return func(*args, **kwargs)
  File "D:\spiders\tk-auto-study\main.py", line 164, in run
    single_study(username, pwd, pub_key)
  File "D:\spiders\tk-auto-study\main.py", line 137, in single_study
    login(username, password, pub_key)
  File "D:\spiders\tk-auto-study\main.py", line 100, in login
    code = api.get_validate_code()
  File "D:\spiders\tk-auto-study\api_module\main_api.py", line 54, in get_validate_code
    resp = sess.get(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.%3Cattribute%20'microsecond'%20of%20'datetime.datetime'%20objects%3E&width=58&height=19&num=4 (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

**Comment by yating1022** [comment]
运行是正常的，就是学习了新的系统上也没有记录

**Comment by 838239178** [comment]
@yating1022 新系统是独立的

**Comment by Byrtesc** [comment]
> 运行是正常的，就是学习了新的系统上也没有记录

新系统是独立的，而且会计算时长，时长不够不予记录到新系统中

**Comment by 838239178** [comment]
我们这也通知更换了 大寄

**Comment by 838239178** [comment]
研究了一下这个系统：

- 登陆方式均为wxLogin，通过wx服务器生成的code换取jwt
- token刷新依赖wxLogin
- openid无法成为学习记录的识别标志
- 学习记录生成流程仅为一个POST请求
- 所有HTTP请求均需要生成签名，目前签名算法已经知晓，但是模拟请求仍未成功

根据现有的信息得出，暂时无法实现全自动化

**Comment by 838239178** [comment]
最新进展,成功实现了抓取token并一次性完成了所有课课程。发现一个非常有意思的Bug，学习记录的名称是由前端决定的，于是就诞生了以下画面（重复请求一个课程id可以覆盖名称）
![image](https://user-images.githubusercontent.com/55338151/192083574-08a56fce-f538-4eb7-bf82-ebc002927643.png)

**Comment by 838239178** [comment]
token有效期为一周，存在refresh_token，意味着token刷新可能不需要依赖微信登陆，目前找不到token刷新的api，需要到期后登陆账号查看流程。运气好的话只需要抓包一次就能一劳永逸。

**Comment by dawnli-github** [comment]
cool，期待上线

**Comment by cxy5014** [comment]
可以参考下这个refresh_token方式？

https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html

**Comment by 838239178** [comment]
@cxy5014 与微信无关

**Comment by cxy5014** [comment]
通过抓包发现refreshcode由以下链接产生
https://fjqndxx.iyunci.cn/api/app/big_study/platform/checkuser?code=&appid=wxd6d3fbd320f6116e&platform=3

**Comment by cxy5014** [comment]
通过抓包发现refreshcode由以下链接产生
https://fjqndxx.iyunci.cn/api/app/big_study/platform/checkuser?code=&appid=&platform=
此链接由微信跳转产生

**Comment by 838239178** [comment]
> 通过抓包发现refreshcode由以下链接产生
> 
> https://fjqndxx.iyunci.cn/api/app/big_study/platform/checkuser?code=&appid=&platform=
> 
> 此链接由微信跳转产生
> 
> 

这个我知道

**Comment by HolyDomain** [comment]
> 最新进展,成功实现了抓取token并一次性完成了所有课课程。发现一个非常有意思的Bug，学习记录的名称是由前端决定的，于是就诞生了以下画面（重复请求一个课程id可以覆盖名称） ![image](https://user-images.githubusercontent.com/55338151/192083574-08a56fce-f538-4eb7-bf82-ebc002927643.png)

哥们截图暴露名字了

**Comment by 838239178** [comment]
@HolyDomain 危

**Comment by 838239178** [comment]
已经知晓token刷新方法，确实只需要抓包一次就能实现全自动化，但是官方存在检测手段，我已被警告😅

**Comment by Genicur** [comment]
> 已经知晓token刷新方法，确实只需要抓包一次就能实现全自动化，但是官方存在检测手段，我已被警告😅

绷不住啦

**Comment by 838239178** [comment]
@Genicur 我是刚好碰到漏洞，留了一个篡改记录，来个勇士替我完成😃

**Comment by Genicur** [comment]
> @Genicur 我是刚好碰到漏洞，留了一个篡改记录，来个勇士替我完成😃

Traceback (most recent call last):
  File "/root/tk-auto-study/main.py", line 7, in <module>
    from api_module import main_api as api
  File "/root/tk-auto-study/api_module/main_api.py", line 6, in <module>
    from entity_module import UserInfo, TokenInfo, CourseInfo
  File "/root/tk-auto-study/entity_module/__init__.py", line 2, in <module>
    from config import Config
ModuleNotFoundError: No module named 'config'
拉了v2的库 缺了这个依赖 但是没有在requirements.txt里找到。。 是不是自己写的

**Comment by 838239178** [comment]
> > @Genicur 我是刚好碰到漏洞，留了一个篡改记录，来个勇士替我完成😃
> 
> Traceback (most recent call last): File "/root/tk-auto-study/main.py", line 7, in from api_module import main_api as api File "/root/tk-auto-study/api_module/main_api.py", line 6, in from entity_module import UserInfo, TokenInfo, CourseInfo File "/root/tk-auto-study/entity_module/**init**.py", line 2, in from config import Config ModuleNotFoundError: No module named 'config' 拉了v2的库 缺了这个依赖 但是没有在requirements.txt里找到。。 是不是自己写的

更新了
