### ISSUE TITLE
请问现在是用不了了吗？

### ISSUE THREAD

**Issue by ChampionChann** [838239178/tk-auto-study#103]
### 使用的Python版本

3.7

### 使用的发行版本

1.3.4

### 运行平台

local/server

### 问题描述

青龙运行报错

### 运行日志

[INFO]:正在登录尾号6563
[INFO]:消息推送成功
[ERROR]:异常信息: 请阅读异常提醒，如果无法解决请截图日志发issue)：HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.%3Cattribute%20'microsecond'%20of%20'datetime.datetime'%20objects%3E&width=58&height=19&num=4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f68e8a57580>, 'Connection to m.fjcyl.com timed out. (connect timeout=5)'))
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f68e8a57580>, 'Connection to m.fjcyl.com timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.%3Cattribute%20'microsecond'%20of%20'datetime.datetime'%20objects%3E&width=58&height=19&num=4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f68e8a57580>, 'Connection to m.fjcyl.com timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/scripts/tk-auto-study/main.py", line 20, in catch
    return func(*args, **kwargs)
  File "/ql/scripts/tk-auto-study/main.py", line 172, in run
    multi_study(accounts, pub_key)
  File "/ql/scripts/tk-auto-study/main.py", line 134, in multi_study
    login(account['username'], account['pwd'], pub_key)
  File "/ql/scripts/tk-auto-study/main.py", line 110, in login
    code = api.get_validate_code()
  File "/ql/scripts/tk-auto-study/api_module/main_api.py", line 54, in get_validate_code
    resp = sess.get(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.%3Cattribute%20'microsecond'%20of%20'datetime.datetime'%20objects%3E&width=58&height=19&num=4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f68e8a57580>, 'Connection to m.fjcyl.com timed out. (connect timeout=5)'))

**Comment by 838239178** [comment]
待排查

**Comment by KimLay233** [comment]
> 待排查

请问报错验证码发送失败，unknown client id
是为什么？是不是之前的账号不能用了？

**Comment by 838239178** [comment]
@KimLay233 ocr配置有问题

**Comment by KimLay233** [comment]
> @KimLay233 ocr配置有问题

好的，谢谢！

**Comment by ChampionChann** [comment]
您好，我用的是main.py，这边看到您修复的文件是main_api.py，目前问题依然存在

**Comment by 838239178** [comment]
合并了
