### ISSUE TITLE
v2 分支反馈

### ISSUE THREAD

**Issue by 838239178** [838239178/tk-auto-study#111]
### 内容

成功执行的反馈一下，失败的也可以反馈，被警告的也请反馈

**Comment by hxp1999** [comment]
抓到的expire和refreshExpire是这样的：

> "expire": 7200,
    "refreshExpire": 432000,

运行后直接提示token and refreashToken has expired

**Comment by hxp1999** [comment]
还有就是config里是否还要加上openid等信息？

**Comment by 838239178** [comment]
> 还有就是config里是否还要加上openid等信息？

不需要

**Comment by dierwang101** [comment]
抓办完填写完配置运行出错了。以为是用了serverchan出了问题，把推送配置清空还是报错，不知道哪里出了问题。下面是出错日志：
`
C:\Users\Administrator\.conda\envs\xxqg\python.exe "E:/machine learing/tk-auto-study-2/main.py"
Traceback (most recent call last):
  File "E:/machine learing/tk-auto-study-2/main.py", line 7, in <module>
    from api_module import main_api as api
  File "E:\machine learing\tk-auto-study-2\api_module\main_api.py", line 5, in <module>
    from api_module.sign import get_ts, use_sign
  File "E:\machine learing\tk-auto-study-2\api_module\sign.py", line 13, in <module>
    def use_sign(dt) -> tuple[str, str]:
TypeError: 'type' object is not subscriptable
`

**Comment by 838239178** [comment]
@dierwang101 可能需要py3.9的版本

**Comment by Githubsanae** [comment]
运行报错信息
`requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
## 运行环境
win10 20h2

python3.10和python3.9都试过

## 配置文件截图
![2022-10-11_13-31-25](https://user-images.githubusercontent.com/91273244/195005280-13200a92-94a4-4050-a76f-d593004b825e.png)


## 完整报错信息
```
C:\ProgramData\Anaconda3\envs\mysql_python\python.exe "F:/Python/qndxx V2/tk-auto-study/main.py"
[INFO]:你正在使用本地服务,请确保填写了配置文件
[INFO]:自动学习开始
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mysql_python\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\mysql_python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\envs\mysql_python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\envs\mysql_python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Python\qndxx V2\tk-auto-study\main.py", line 117, in <module>
    start_local()
  File "F:\Python\qndxx V2\tk-auto-study\main.py", line 113, in start_local
    run(True)
  File "F:\Python\qndxx V2\tk-auto-study\main.py", line 27, in catch
    error_exit(f"请阅读异常提醒，如果无法解决请截图日志发issue)：{e}")
  File "F:\Python\qndxx V2\tk-auto-study\main.py", line 37, in error_exit
    sendutil.send_msg(content=msg, success=False)
  File "F:\Python\qndxx V2\tk-auto-study\send_module\util.py", line 38, in send_msg
    res = sender.executor\
  File "F:\Python\qndxx V2\tk-auto-study\send_module\server_chan\sender.py", line 18, in send
    send_res = resp.json()
  File "C:\ProgramData\Anaconda3\envs\mysql_python\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by dierwang101** [comment]
> 

使用py3.9后可以使用，但是仍然出错。日志如下：
`
[INFO]:你正在使用本地服务,请确保填写了配置文件
[INFO]:自动学习开始
[ERROR]:异常信息: token and refreashToken has expired
`

**Comment by 838239178** [comment]
@Githubsanae 这个问题以及修复

**Comment by 838239178** [comment]
@dierwang101 @hxp1999  API发生了改动需要重新分析

**Comment by 838239178** [comment]
已更新
