### ISSUE TITLE
用不了了

### ISSUE THREAD

**Issue by 1622663850** [838239178/tk-auto-study#13]
最近用不了呐，提示登录错误

**Comment by 838239178** [comment]
请把完整的日志贴上来

**Comment by 1622663850** [comment]
Run python3 workflow.py <<EOF
[INFO]:auto-study is Running
Traceback (most recent call last):
  File "workflow.py", line 4, in <module>
    main.start_with_workflow()
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 120, in start_with_workflow
    run(False)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 100, in run
    code = get_validate_code()
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 33, in get_validate_code
    res = ocr.netpic_ocr(base64.b64encode(resp.content))
  File "/home/runner/work/tk-auto-study/tk-auto-study/baidu_image/ocr.py", line 64, in netpic_ocr
    access_token = tokens.get_token(_API_KEY, _SECRET_KEY)
  File "/home/runner/work/tk-auto-study/tk-auto-study/baidu_image/tokens.py", line 12, in get_token
    raise Exception(response.json().get('error_description'))
Exception: Client authentication failed
Error: Process completed with exit code 1.

**Comment by 838239178** [comment]
已定位问题 耐心等待解决
