### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HolyDomain** [838239178/tk-auto-study#26]
运行最新版本出现错误提示：Open api qps request limit reached
百度云刚刚已实名，免费使用额度刚刚领取

**Comment by HolyDomain** [comment]
Run python3 workflow.py
[INFO]:你正在使用GitHubAction,请确保secret已经配置
[INFO]:自动学习开始
[INFO]:使用 OCR baidu_image
Warning: :获取验证码失败，原因:Open api qps request limit reached
Warning: :正在重试, 次数:0
Warning: :获取验证码失败，原因:Open api qps request limit reached
Warning: :正在重试, 次数:1
Warning: :获取验证码失败，原因:Open api qps request limit reached
Warning: :正在重试, 次数:2
Warning: :获取验证码失败，原因:Open api qps request limit reached
Warning: :正在重试, 次数:3
Warning: :获取验证码失败，原因:Open api qps request limit reached
Warning: :正在重试, 次数:4
Error: :验证码解析失败,请尝试更换方式或发issue寻求帮助
NoneType: None
Error: :发生未知异常(请截图日志发issue)：No active exception to reraise
Traceback (most recent call last):
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 36, in catch
    return func(*args, **kwargs)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 206, in run
    login(username, pwd, pub_key)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 139, in login
    code = get_validate_code()
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 69, in get_validate_code
    error_exit("验证码解析失败,请尝试更换方式或发issue寻求帮助")
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 50, in error_exit
    raise
RuntimeError: No active exception to reraise
Traceback (most recent call last):
  File "workflow.py", line 4, in <module>
    main.start_with_workflow()
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 216, in start_with_workflow
    run(False)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 38, in catch
    error_exit(f"发生未知异常(请截图日志发issue)：{e}")
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 36, in catch
    return func(*args, **kwargs)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 206, in run
    login(username, pwd, pub_key)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 139, in login
    code = get_validate_code()
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 69, in get_validate_code
    error_exit("验证码解析失败,请尝试更换方式或发issue寻求帮助")
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 50, in error_exit
    raise
RuntimeError: No active exception to reraise
Error: Process completed with exit code 1.

**Comment by HolyDomain** [comment]
估计是刚刚领取有延迟，可以了
