### ISSUE TITLE
GitHub actions中server酱无法正常使用[BUG]

### ISSUE THREAD

**Issue by HolyDomain** [838239178/tk-auto-study#27]
## 问题描述
GitHub actions中server酱无法正常使用

**Comment by HolyDomain** [comment]
Run python3 workflow.py
  python3 workflow.py
  shell: /usr/bin/bash -e {0}
  env:
    username: ***
    password: ***
    pubKey: ***
    ocrSecret: ***
    ocrKey: ***
    ocrType: 
    sendType: ***
    sendKey: ***
    sendMode: ***
[INFO]:你正在使用GitHubAction,请确保secret已经配置
[INFO]:自动学习开始
[INFO]:使用 OCR baidu_image
Traceback (most recent call last):
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 36, in catch
    return func(*args, **kwargs)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 204, in run
    init_sender(send_type, send_key, send_mode)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 173, in init_sender
    send_util['sender'] = importlib.import_module(f"send_module.{send_type}.sender")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'send_module.***'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "workflow.py", line 4, in <module>
    main.start_with_workflow()
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 216, in start_with_workflow
    run(False)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 38, in catch
    error_exit(f"发生未知异常(请截图日志发issue)：{e}")
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 48, in error_exit
    send_msg(content=msg, success=False)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 185, in send_msg
    res = send_util['sender'].send(title="青年大学习打卡",
KeyError: 'sender'
Error: Process completed with exit code 1.

**Comment by 838239178** [comment]
检查你的secrets配置 send_type
