### ISSUE TITLE
执行错误

### ISSUE THREAD

**Issue by dawnli-github** [838239178/tk-auto-study#3]
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    run(True)
  File "main.py", line 97, in run
    post_login(username, pwd, code, pub_key)
  File "main.py", line 68, in post_login
    logging.info('login ' + resp.json().get('errmsg'))
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by 838239178** [comment]
@dawnli-github 
从日志上来考虑是官方服务器发生错误，导致返回信息非json格式。尝试重新运行脚本。
我这边的日志也报了同样错误，是官方服务器问题。

**Comment by dawnli-github** [comment]
好嘞，非常感谢

**Comment by 838239178** [comment]
> 好嘞，非常感谢

这边我检验了一下 服务器那边肯能新加了某些验证手段 导致发出的post请求识别成了get 这个bug有待研究 目前脚本无法正常运行

**Comment by 838239178** [comment]
> 好嘞，非常感谢

官方服务器服务采用了https协议 导致发生bug 目前正在修复 请关注最新提交

**Comment by 838239178** [comment]
@dawnli-github 
已修复
