### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 2451965602** [838239178/tk-auto-study#47]
Pulling image library/python:3.7.4
Loading assets
+ pip install -r requirements.txt
Collecting requests
  Using cached https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl
Processing /root/.cache/pip/wheels/a0/6d/55/ec88dcdc4147fd713c31d916a500c147a28caca0d134027dfe/gmssl-3.2.1-cp37-none-any.whl
Collecting pycryptodome
  Using cached https://files.pythonhosted.org/packages/71/6b/965be3bec8fc1f6013739fea2bba86cf43a3be09ab7e29bd2134829c7615/pycryptodome-3.14.1-cp35-abi3-manylinux2010_x86_64.whl
Collecting certifi>=2017.4.17
  Using cached https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl
Collecting idna<4,>=2.5; python_version >= "3"
  Using cached https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1
  Using cached https://files.pythonhosted.org/packages/4e/b8/f5a25b22e803f0578e668daa33ba3701bb37858ec80e08a150bd7d2cf1b1/urllib3-1.26.8-py2.py3-none-any.whl
Collecting charset-normalizer~=2.0.0; python_version >= "3"
  Using cached https://files.pythonhosted.org/packages/06/b3/24afc8868eba069a7f03650ac750a778862dc34941a4bebeb58706715726/charset_normalizer-2.0.12-py3-none-any.whl
Installing collected packages: certifi, idna, urllib3, charset-normalizer, requests, gmssl, pycryptodome
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.12 gmssl-3.2.1 idna-3.3 pycryptodome-3.14.1 requests-2.27.1 urllib3-1.26.8
WARNING: You are using pip version 19.3; however, version 22.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ python3 main.py
[INFO]:你正在使用本地服务,请确保填写了配置文件
[INFO]:自动学习开始
[INFO]:使用 OCR baidu_image
[INFO]:开始多人打卡，人数2
[INFO]:正在登录尾号
[ERROR]:异常信息: 请阅读异常提醒，如果无法解决请截图日志发issue)：HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.123123&width=58&height=19&num=4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19f38dfed0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f19f38dfed0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.123123&width=58&height=19&num=4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19f38dfed0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 39, in catch
    return func(*args, **kwargs)
  File "main.py", line 271, in run
    multi_study(accounts, pub_key)
  File "main.py", line 235, in multi_study
    login(account['username'], account['pwd'], pub_key)
  File "main.py", line 163, in login
    code = get_validate_code()
  File "main.py", line 65, in get_validate_code
    resp = sess.get(url="https://m.fjcyl.com/validateCode?0.123123&width=58&height=19&num=4")
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.123123&width=58&height=19&num=4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19f38dfed0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Action failed: see logs above for details
Container exited with status code other than 0

**Comment by 838239178** [comment]
你是用了国外的服务器吗
