### ISSUE TITLE
已经输入百度OCR的API Key和Secret Key 还出现这种情况

### ISSUE THREAD

**Issue by zhypocritical** [838239178/tk-auto-study#5]
Run python3 workflow.py <<EOF
  python3 workflow.py <<EOF
  ***
  ***
  ***
  
  ***
  ***
  EOF
  shell: /usr/bin/bash -e {0}
WARNING:root:config.json:读取config配置文件出错，请确保ocr所需key已经正确输入, 错误信息[Errno 2] No such file or directory: 'config.json'
INFO:root:auto-study is Running
Traceback (most recent call last):
  File "workflow.py", line 4, in <module>
    main.start_with_workflow()
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 120, in start_with_workflow
    run(False)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 100, in run
    code = get_validate_code()
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 33, in get_validate_code
    res = ocr.netpic_ocr(base64.b64encode(resp.content))
  File "/home/runner/work/tk-auto-study/tk-auto-study/baidu_image/ocr.py", line 64, in netpic_ocr
    access_token = tokens.get_token(_API_KEY, _SECRET_KEY)
  File "/home/runner/work/tk-auto-study/tk-auto-study/baidu_image/tokens.py", line 12, in get_token
    raise Exception(response.json().get('error_description'))
Exception: The request is missing a required parameter
Error: Process completed with exit code 1.

**Comment by zhypocritical** [comment]
ocr_api_key     ocr_secret_key 
对着这两输的

**Comment by zhypocritical** [comment]
ok解决了 去baidu_image/ocr.py 中输入就好了

**Comment by 838239178** [comment]
@zhypocritical 请注意这个是WARNING 如果你使用GitHubActions 是可以忽略则个的 可以正常运行 你只需要确保secret有输入即可:smile

**Comment by 838239178** [comment]
> ok解决了 去baidu_image/ocr.py 中输入就好了

你是不是改了run.yml?
