### ISSUE TITLE
[BUG] 无法运行main.py

### ISSUE THREAD

**Issue by dawnli-github** [838239178/tk-auto-study#53]
## 问题描述

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from proxy_module.proxy_fetcher import ProxyFecher
  File "/root/project/temp/tk-auto-study/proxy_module/proxy_fetcher.py", line 7, in <module>
    class ProxyFecher(object):
  File "/root/project/temp/tk-auto-study/proxy_module/proxy_fetcher.py", line 9, in ProxyFecher
    cache_hosts: list[str]
TypeError: 'type' object is not subscriptable

## 使用的版本

python 3.8.10

Package                Version
---------------------- --------------------
attrs                  19.3.0
Automat                0.8.0
blinker                1.4
certifi                2019.11.28
chardet                3.0.4
Click                  7.0
cloud-init             20.1
colorama               0.4.3
command-not-found      0.3
configobj              5.0.6
constantly             15.1.0
cryptography           2.8
dblatex                0.3.11py3
dbus-python            1.2.16
distro                 1.4.0
distro-info            0.23ubuntu1
entrypoints            0.3
exception              0.1.0
gmssl                  3.2.1
httplib2               0.14.0
hyperlink              19.0.0
idna                   2.8
importlib-metadata     1.5.0
incremental            16.10.1
isc                    2.0
Jinja2                 2.10.1
jsonpatch              1.22
jsonpointer            2.0
jsonschema             3.2.0
keyring                18.0.1
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
lxml                   4.8.0
MarkupSafe             1.1.0
more-itertools         4.2.0
netifaces              0.10.4
oauthlib               3.1.0
pip                    22.0.4
ply                    3.11
pyasn1                 0.4.2
pyasn1-modules         0.2.1
pycryptodome           3.14.1
pycurl                 7.43.0.2
PyGObject              3.36.0
PyHamcrest             1.9.0
PyJWT                  1.7.1
pymacaroons            0.13.0
PyNaCl                 1.3.0
pyOpenSSL              19.0.0
pyrsistent             0.15.5
pyserial               3.4
python-apt             2.0.0+ubuntu0.20.4.6
python-debian          0.1.36ubuntu1
PyYAML                 5.3.1
regex                  2022.3.15
requests               2.22.0
requests-unixsocket    0.2.0
SecretStorage          2.3.1
service-identity       18.1.0
setuptools             45.2.0
simplejson             3.16.0
six                    1.14.0
ssh-import-id          5.10
systemd-python         234
Twisted                18.9.0
ubuntu-advantage-tools 20.3
ufw                    0.36
unattended-upgrades    0.1
urllib3                1.25.8
wadllib                1.3.3
wheel                  0.34.2
zipp                   1.0.0
zope.interface         4.7.1

## 完整的运行日志

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from proxy_module.proxy_fetcher import ProxyFecher
  File "/root/project/temp/tk-auto-study/proxy_module/proxy_fetcher.py", line 7, in <module>
    class ProxyFecher(object):
  File "/root/project/temp/tk-auto-study/proxy_module/proxy_fetcher.py", line 9, in ProxyFecher
    cache_hosts: list[str]
TypeError: 'type' object is not subscriptable
```

**Comment by dawnli-github** [comment]
已解决，建议把python版本需求放在readme，然后proxy可以在json里放个选项，这样下次更新的时候就不会冲突了
