### ISSUE TITLE
[询问]import的时候报错

### ISSUE THREAD

**Issue by zidou-kiyn** [838239178/tk-auto-study#59]
Traceback (most recent call last):
  File "C:/Users/30387/Desktop/tk-auto-study-1.2.7/main.py", line 15, in <module>
    from proxy_module.proxy_fetcher import ProxyFecher
  File "C:\Users\30387\Desktop\tk-auto-study-1.2.7\proxy_module\proxy_fetcher.py", line 7, in <module>
    class ProxyFecher(object):
  File "C:\Users\30387\Desktop\tk-auto-study-1.2.7\proxy_module\proxy_fetcher.py", line 9, in ProxyFecher
    cache_hosts: list[str]
TypeError: 'type' object is not subscriptable

不是很理解

**Comment by zidou-kiyn** [comment]
看到其他issue已解决
