### ISSUE TITLE
[BUG] send_res['code']报错 

### ISSUE THREAD

**Issue by zidou-kiyn** [838239178/tk-auto-study#60]
## 问题描述
KeyError: 'code'
## 使用的版本
1.2.7
**python:**[e.g. 3.9.7]
**version:**[e.g. 1.2.7]

## 完整的运行日志

Traceback (most recent call last):
  File "E:\Products\tk-auto-study-1.2.7\main.py", line 330, in <module>
    run(True)
  File "E:\Products\tk-auto-study-1.2.7\main.py", line 49, in catch
    error_exit(f"请阅读异常提醒，如果无法解决请截图日志发issue)：{e}")
  File "E:\Products\tk-auto-study-1.2.7\main.py", line 60, in error_exit
    send_msg(content=msg, success=False)
  File "E:\Products\tk-auto-study-1.2.7\main.py", line 237, in send_msg
    res = send_util['sender'].send(title="青年大学习打卡",
  File "E:\Products\tk-auto-study-1.2.7\send_module\server_chan\sender.py", line 19, in send
    success = send_res['code'] == 0
KeyError: 'code'

**Comment by zidou-kiyn** [comment]
send_res的值为{'message': 'Custom authentication failed: authentication information, incorrect'}
是我配置有问题嘛？
可是我key填的就是serverchan的SendKey

**Comment by zidou-kiyn** [comment]
已解决 serverchan每天的发送消息有限制
