### ISSUE TITLE
[BUG] 卡在登陆

### ISSUE THREAD

**Issue by 2463422967** [838239178/tk-auto-study#61]
## 问题描述
在centos7上运行一直卡在正在登陆
## 使用的版本

**python:**[e.g. 3.9]
**version:**[e.g. 1.2.2]

## 完整的运行日志
[root@localhost tk-auto-study-master]# python main.py 
[INFO]:你正在使用本地服务,请确保填写了配置文件
[INFO]:自动学习开始
[INFO]:开始多人打卡，人数53
[INFO]:正在登录尾号9360

```text

```

**Comment by 2463422967** [comment]
[ERROR]:异常信息: 官方服务器发生异常,错误代码:502,信息:<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>






NoneType: None
[ERROR]:异常信息: 请阅读异常提醒，如果无法解决请截图日志发issue)：-1
Traceback (most recent call last):
  File "/home/python/qndxx/tk-auto-study-master/main.py", line 40, in catch
    return func(*args, **kwargs)
  File "/home/python/qndxx/tk-auto-study-master/main.py", line 273, in run
    multi_study(accounts, pub_key)
  File "/home/python/qndxx/tk-auto-study-master/main.py", line 237, in multi_study
    login(account['username'], account['pwd'], pub_key)
  File "/home/python/qndxx/tk-auto-study-master/main.py", line 166, in login
    post_login(username, pwd, pub_key)
  File "/home/python/qndxx/tk-auto-study-master/main.py", line 114, in post_login
    error_exit(f'官方服务器发生异常,错误代码:{resp.status_code},信息:{resp.text}')
  File "/home/python/qndxx/tk-auto-study-master/main.py", line 63, in error_exit
    exit(-1)
  File "/usr/local/python3/lib/python3.9/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: -1
后续多次尝试可以往下运行 然后报错

**Comment by zidou-kiyn** [comment]
502就是共青团网站的问题了 官网的服务器经常崩 经常遇到同学进不去做不了的情况

**Comment by 838239178** [comment]
#62
