### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 17850773959** [838239178/tk-auto-study#62]
Error: :异常信息: 请阅读异常提醒，如果无法解决请截图日志发issue)：-1
Traceback (most recent call last):
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 40, in catch
    return func(*args, **kwargs)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 273, in run
    multi_study(accounts, pub_key)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 237, in multi_study
    login(account['username'], account['pwd'], pub_key)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 166, in login
    post_login(username, pwd, pub_key)
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 114, in post_login
    error_exit(f'官方服务器发生异常,错误代码:{resp.status_code},信息:{resp.text}')
  File "/home/runner/work/tk-auto-study/tk-auto-study/main.py", line 63, in error_exit
    exit(-1)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: -1
Error: Process completed with exit code 255.

**Comment by zidou-kiyn** [comment]
一般是共青团官网的问题吧 换个时间段

**Comment by 838239178** [comment]
已经回复
