### ISSUE TITLE
[BUG]无法使用宝塔计划任务执行

### ISSUE THREAD

**Issue by HsukqiLee** [838239178/tk-auto-study#63]
## 问题描述

将程序git clone了一份到服务器上，
使用ssh登录root账号，执行
```
cd /.../
python3 main.py
```
可以正常登录打卡，
但是使用宝塔计划任务添加**Shell脚本**任务，无论是手动执行还是自动运行，都会报错误，如下。

## 使用的版本

**python:**3.6
**version:**1.2.3

## 完整的运行日志

```text
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    encryptor = importlib.import_module(f"crypt_module.{crypt_name}.{crypt_name}_{crypt_mode}")
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/.../crypt_module/sm4/sm4_ecb.py", line 1, in <module>
    from gmssl.sm4 import CryptSM4, SM4_ENCRYPT, SM4_DECRYPT
ModuleNotFoundError: No module named 'gmssl'
```

**Comment by zidou-kiyn** [comment]
试一下python3.9?

**Comment by HsukqiLee** [comment]
> 试一下python3.9?

我试过了，发现可能是以下原因：

 1.服务器上有两个磁盘，挂载在/和/data
 2.运行目录在/www/wwwroot/xxx/，/www/wwwroot/是指向/data/wwwroot/的软链接

更新至最新版，更换python版本后也是报这样的错误。

**Comment by HsukqiLee** [comment]
经排查，就是使用python3.9运行，但是是因为以下原因：

 1. 服务器上python3有两个，python3.6和python3.9
 2. /usr/bin/python3为python3.9，环境变量也是python3.9
 3. 但是/usr/bin目录下并没有python3.9

解决方法：
`ln -s /usr/local/python3/bin/python3.9 /usr/bin/python3.9`

说明：
当对应环境没有设置恰当软链接时，会出现使用pythonX可以执行，/usr/bin/pythonX不可以执行的情况，而计划任务中默认使用/usr/bin/pythonX调用命令。

感谢其他contributors的回复。
