### ISSUE TITLE
[BUG]服务器端无法正常运行： TypeError：“类型”对象不可下标

### ISSUE THREAD

**Issue by HolyDomain** [838239178/tk-auto-study#66]
## 问题描述
服务器端无法正常运行

## 使用的版本

**Python 3.7.4
**version:1.2.8

## 完整的运行日志

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from proxy_module.proxy_fetcher import ProxyFecher
  File "/root/tk-auto-study/proxy_module/proxy_fetcher.py", line 7, in <module>
    class ProxyFecher(object):
  File "/root/tk-auto-study/proxy_module/proxy_fetcher.py", line 9, in ProxyFecher
    cache_hosts: list[str]
TypeError: 'type' object is not subscriptable

**Comment by 838239178** [comment]
需要python 3.9

**Comment by 838239178** [comment]
使用python3.9
