### ISSUE TITLE
[BUG]打卡超时

### ISSUE THREAD

**Issue by abin-zh** [838239178/tk-auto-study#76]
[ERROR]:异常信息: 请阅读异常提醒，如果无法解决请截图日志发issue)：HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retr     ies exceeded with url: /studyRecord (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7759645     50>, 'Connection to m.fjcyl.com timed out. (connect timeout=5)'))
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/python3/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/python3/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/python3/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/python3/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fc775964550>, 'Connection to m.fjcy     l.com timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/python3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/python3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /studyRec     ord (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc775964550>, 'Connection to m.fjcyl.com      timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tk-auto-study/main.py", line 42, in catch
    return func(*args, **kwargs)
  File "/root/tk-auto-study/main.py", line 250, in run
    multi_study(accounts, pub_key)
  File "/root/tk-auto-study/main.py", line 215, in multi_study
    post_study_record()
  File "/root/tk-auto-study/main.py", line 77, in post_study_record
    resp = sess.post(url="https://m.fjcyl.com/studyRecord", timeout=5)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /studyR     ecord (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc775964550>, 'Connection to m.fjcyl.co     m timed out. (connect timeout=5)'))

**Comment by 838239178** [comment]
超时时间太短了 已经修改
