### ISSUE TITLE
[询问]为什么用crontab就会报错No module named 'gmssl' 但是在终端手动运行就不报错

### ISSUE THREAD

**Issue by julynet** [838239178/tk-auto-study#78]
以下为报错log
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    f"crypt_module.{CRYPT_NAME}.{CRYPT_NAME}_{CRYPT_MODE}")
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/tk/crypt_module/sm4/sm4_ecb.py", line 1, in <module>
    from gmssl.sm4 import CryptSM4, SM4_ENCRYPT, SM4_DECRYPT
ModuleNotFoundError: No module named 'gmssl'

以下为手动运行log
[root@VM-8-2-centos tk]# python3 main.py
[INFO]:你正在使用本地服务,请确保填写了配置文件
[INFO]:自动学习开始
[INFO]:开始单人打卡
[INFO]:正在登录尾号4912
[INFO]:4912 login 登录成功！
[INFO]:学习成功！
True
[INFO]:消息推送成功

以下为crontab规则
00 15 * * 2,0 cd /root/tk && python3 main.py >> crontab.log 2>&1

**Comment by 838239178** [comment]
这就比较奇怪了🤔

**Comment by julynet** [comment]
> 这就比较奇怪了🤔

明明我安装了这个依赖 是依赖安装目录的问题吗（小白不太懂

**Comment by 838239178** [comment]
你可以试着 不用cd 直接python /xx/main.py

**Comment by julynet** [comment]
![R8912ZOA3 VSLTOBKV9@Y~V](https://user-images.githubusercontent.com/93466263/173517262-f9c57491-87d6-4c86-b40a-2277655b752e.png)
![7Z4KTM4BB)C6L{2LAU_M)XU](https://user-images.githubusercontent.com/93466263/173517371-30ffceef-0bb5-4903-9218-6c94be3bc3ee.png)



> 你可以试着 不用cd 直接python /xx/main.py

**Comment by julynet** [comment]
你能复现吗 还是我环境问题

**Comment by 838239178** [comment]
吧依赖卸掉重装看看，直接输入python进入shell界面然后试试能不能import gmssl

**Comment by 838239178** [comment]
你没有填写配置文件

**Comment by julynet** [comment]
> 你没有填写配置文件

emmm 怎么说呢 给你截个图
![1X%O} CUJOB WE30Q~`Y7 V](https://user-images.githubusercontent.com/93466263/173741912-e6430181-ebdc-412b-ad82-274b4ef25c8c.png)

**Comment by 838239178** [comment]
这我真的没见过这么离谱的

**Comment by 838239178** [comment]
已将config.json改为绝对地址
