### ISSUE TITLE
连接超时 Errno 110 

### ISSUE THREAD

**Issue by julynet** [838239178/tk-auto-study#94]
### 内容

HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.%3Cattribute%20'microsecond'%20of%20'datetime.datetime'%20objects%3E&width=58&height=19&num=4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffa8503cbd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

**Comment by 838239178** [comment]
重试

**Comment by julynet** [comment]
> 重试

是连接问题吗 我昨天重试了几次没用 （没用http代理） 才发的issue 但是刚刚试了是ok的
